// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/message/v1/message.proto

package messagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChatId           string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderId         string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Type             string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Payload          *MessagePayload        `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	ClientMsgId      string                 `protobuf:"bytes,5,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	ReplyToMessageId string                 `protobuf:"bytes,6,opt,name=reply_to_message_id,json=replyToMessageId,proto3" json:"reply_to_message_id,omitempty"`
	ForwardedFrom    *ForwardedFrom         `protobuf:"bytes,7,opt,name=forwarded_from,json=forwardedFrom,proto3" json:"forwarded_from,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_message_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendMessageRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SendMessageRequest) GetPayload() *MessagePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendMessageRequest) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendMessageRequest) GetReplyToMessageId() string {
	if x != nil {
		return x.ReplyToMessageId
	}
	return ""
}

func (x *SendMessageRequest) GetForwardedFrom() *ForwardedFrom {
	if x != nil {
		return x.ForwardedFrom
	}
	return nil
}

type MessagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	MediaId       string                 `protobuf:"bytes,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Caption       string                 `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePayload) Reset() {
	*x = MessagePayload{}
	mi := &file_proto_message_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePayload) ProtoMessage() {}

func (x *MessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePayload.ProtoReflect.Descriptor instead.
func (*MessagePayload) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessagePayload) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MessagePayload) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *MessagePayload) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *MessagePayload) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MessagePayload) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ForwardedFrom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardedFrom) Reset() {
	*x = ForwardedFrom{}
	mi := &file_proto_message_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardedFrom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardedFrom) ProtoMessage() {}

func (x *ForwardedFrom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardedFrom.ProtoReflect.Descriptor instead.
func (*ForwardedFrom) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *ForwardedFrom) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ForwardedFrom) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_message_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UpdateMessageStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageStatusRequest) Reset() {
	*x = UpdateMessageStatusRequest{}
	mi := &file_proto_message_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageStatusRequest) ProtoMessage() {}

func (x *UpdateMessageStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMessageStatusRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *UpdateMessageStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateMessageStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateMessageStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageStatusResponse) Reset() {
	*x = UpdateMessageStatusResponse{}
	mi := &file_proto_message_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageStatusResponse) ProtoMessage() {}

func (x *UpdateMessageStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateMessageStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMessageStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetLastMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatIds       []string               `protobuf:"bytes,1,rep,name=chat_ids,json=chatIds,proto3" json:"chat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastMessagesRequest) Reset() {
	*x = GetLastMessagesRequest{}
	mi := &file_proto_message_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastMessagesRequest) ProtoMessage() {}

func (x *GetLastMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetLastMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetLastMessagesRequest) GetChatIds() []string {
	if x != nil {
		return x.ChatIds
	}
	return nil
}

type GetLastMessagesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Messages      map[string]*MessagePreview `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastMessagesResponse) Reset() {
	*x = GetLastMessagesResponse{}
	mi := &file_proto_message_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastMessagesResponse) ProtoMessage() {}

func (x *GetLastMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetLastMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{7}
}

func (x *GetLastMessagesResponse) GetMessages() map[string]*MessagePreview {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MessagePreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePreview) Reset() {
	*x = MessagePreview{}
	mi := &file_proto_message_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePreview) ProtoMessage() {}

func (x *MessagePreview) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePreview.ProtoReflect.Descriptor instead.
func (*MessagePreview) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{8}
}

func (x *MessagePreview) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessagePreview) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessagePreview) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MessagePreview) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MessagePreview) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetUnreadCountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatIds       []string               `protobuf:"bytes,2,rep,name=chat_ids,json=chatIds,proto3" json:"chat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountsRequest) Reset() {
	*x = GetUnreadCountsRequest{}
	mi := &file_proto_message_v1_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountsRequest) ProtoMessage() {}

func (x *GetUnreadCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountsRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{9}
}

func (x *GetUnreadCountsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUnreadCountsRequest) GetChatIds() []string {
	if x != nil {
		return x.ChatIds
	}
	return nil
}

type GetUnreadCountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        map[string]int64       `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountsResponse) Reset() {
	*x = GetUnreadCountsResponse{}
	mi := &file_proto_message_v1_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountsResponse) ProtoMessage() {}

func (x *GetUnreadCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountsResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{10}
}

func (x *GetUnreadCountsResponse) GetCounts() map[string]int64 {
	if x != nil {
		return x.Counts
	}
	return nil
}

var File_proto_message_v1_message_proto protoreflect.FileDescriptor

const file_proto_message_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/message/v1/message.proto\x12\n" +
	"message.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x02\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x124\n" +
	"\apayload\x18\x04 \x01(\v2\x1a.message.v1.MessagePayloadR\apayload\x12\"\n" +
	"\rclient_msg_id\x18\x05 \x01(\tR\vclientMsgId\x12-\n" +
	"\x13reply_to_message_id\x18\x06 \x01(\tR\x10replyToMessageId\x12@\n" +
	"\x0eforwarded_from\x18\a \x01(\v2\x19.message.v1.ForwardedFromR\rforwardedFrom\"\x96\x01\n" +
	"\x0eMessagePayload\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12\x19\n" +
	"\bmedia_id\x18\x02 \x01(\tR\amediaId\x12\x18\n" +
	"\acaption\x18\x03 \x01(\tR\acaption\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"G\n" +
	"\rForwardedFrom\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"o\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"l\n" +
	"\x1aUpdateMessageStatusRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"7\n" +
	"\x1bUpdateMessageStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x16GetLastMessagesRequest\x12\x19\n" +
	"\bchat_ids\x18\x01 \x03(\tR\achatIds\"\xc1\x01\n" +
	"\x17GetLastMessagesResponse\x12M\n" +
	"\bmessages\x18\x01 \x03(\v21.message.v1.GetLastMessagesResponse.MessagesEntryR\bmessages\x1aW\n" +
	"\rMessagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.message.v1.MessagePreviewR\x05value:\x028\x01\"\xaf\x01\n" +
	"\x0eMessagePreview\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"L\n" +
	"\x16GetUnreadCountsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bchat_ids\x18\x02 \x03(\tR\achatIds\"\x9d\x01\n" +
	"\x17GetUnreadCountsResponse\x12G\n" +
	"\x06counts\x18\x01 \x03(\v2/.message.v1.GetUnreadCountsResponse.CountsEntryR\x06counts\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\x80\x03\n" +
	"\x0eMessageService\x12N\n" +
	"\vSendMessage\x12\x1e.message.v1.SendMessageRequest\x1a\x1f.message.v1.SendMessageResponse\x12f\n" +
	"\x13UpdateMessageStatus\x12&.message.v1.UpdateMessageStatusRequest\x1a'.message.v1.UpdateMessageStatusResponse\x12Z\n" +
	"\x0fGetLastMessages\x12\".message.v1.GetLastMessagesRequest\x1a#.message.v1.GetLastMessagesResponse\x12Z\n" +
	"\x0fGetUnreadCounts\x12\".message.v1.GetUnreadCountsRequest\x1a#.message.v1.GetUnreadCountsResponseB>Z<github.com/whatsapp-clone/backend/proto/message/v1;messagev1b\x06proto3"

var (
	file_proto_message_v1_message_proto_rawDescOnce sync.Once
	file_proto_message_v1_message_proto_rawDescData []byte
)

func file_proto_message_v1_message_proto_rawDescGZIP() []byte {
	file_proto_message_v1_message_proto_rawDescOnce.Do(func() {
		file_proto_message_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_v1_message_proto_rawDesc), len(file_proto_message_v1_message_proto_rawDesc)))
	})
	return file_proto_message_v1_message_proto_rawDescData
}

var file_proto_message_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_message_v1_message_proto_goTypes = []any{
	(*SendMessageRequest)(nil),          // 0: message.v1.SendMessageRequest
	(*MessagePayload)(nil),              // 1: message.v1.MessagePayload
	(*ForwardedFrom)(nil),               // 2: message.v1.ForwardedFrom
	(*SendMessageResponse)(nil),         // 3: message.v1.SendMessageResponse
	(*UpdateMessageStatusRequest)(nil),  // 4: message.v1.UpdateMessageStatusRequest
	(*UpdateMessageStatusResponse)(nil), // 5: message.v1.UpdateMessageStatusResponse
	(*GetLastMessagesRequest)(nil),      // 6: message.v1.GetLastMessagesRequest
	(*GetLastMessagesResponse)(nil),     // 7: message.v1.GetLastMessagesResponse
	(*MessagePreview)(nil),              // 8: message.v1.MessagePreview
	(*GetUnreadCountsRequest)(nil),      // 9: message.v1.GetUnreadCountsRequest
	(*GetUnreadCountsResponse)(nil),     // 10: message.v1.GetUnreadCountsResponse
	nil,                                 // 11: message.v1.GetLastMessagesResponse.MessagesEntry
	nil,                                 // 12: message.v1.GetUnreadCountsResponse.CountsEntry
	(*timestamppb.Timestamp)(nil),       // 13: google.protobuf.Timestamp
}
var file_proto_message_v1_message_proto_depIdxs = []int32{
	1,  // 0: message.v1.SendMessageRequest.payload:type_name -> message.v1.MessagePayload
	2,  // 1: message.v1.SendMessageRequest.forwarded_from:type_name -> message.v1.ForwardedFrom
	13, // 2: message.v1.SendMessageResponse.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: message.v1.GetLastMessagesResponse.messages:type_name -> message.v1.GetLastMessagesResponse.MessagesEntry
	13, // 4: message.v1.MessagePreview.created_at:type_name -> google.protobuf.Timestamp
	12, // 5: message.v1.GetUnreadCountsResponse.counts:type_name -> message.v1.GetUnreadCountsResponse.CountsEntry
	8,  // 6: message.v1.GetLastMessagesResponse.MessagesEntry.value:type_name -> message.v1.MessagePreview
	0,  // 7: message.v1.MessageService.SendMessage:input_type -> message.v1.SendMessageRequest
	4,  // 8: message.v1.MessageService.UpdateMessageStatus:input_type -> message.v1.UpdateMessageStatusRequest
	6,  // 9: message.v1.MessageService.GetLastMessages:input_type -> message.v1.GetLastMessagesRequest
	9,  // 10: message.v1.MessageService.GetUnreadCounts:input_type -> message.v1.GetUnreadCountsRequest
	3,  // 11: message.v1.MessageService.SendMessage:output_type -> message.v1.SendMessageResponse
	5,  // 12: message.v1.MessageService.UpdateMessageStatus:output_type -> message.v1.UpdateMessageStatusResponse
	7,  // 13: message.v1.MessageService.GetLastMessages:output_type -> message.v1.GetLastMessagesResponse
	10, // 14: message.v1.MessageService.GetUnreadCounts:output_type -> message.v1.GetUnreadCountsResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_message_v1_message_proto_init() }
func file_proto_message_v1_message_proto_init() {
	if File_proto_message_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_v1_message_proto_rawDesc), len(file_proto_message_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_message_v1_message_proto_goTypes,
		DependencyIndexes: file_proto_message_v1_message_proto_depIdxs,
		MessageInfos:      file_proto_message_v1_message_proto_msgTypes,
	}.Build()
	File_proto_message_v1_message_proto = out.File
	file_proto_message_v1_message_proto_goTypes = nil
	file_proto_message_v1_message_proto_depIdxs = nil
}
