FROM golang:1.24-alpine

RUN apk add --no-cache git gcc musl-dev
RUN go install github.com/air-verse/air@latest

WORKDIR /app

# Copy go workspace files
COPY go.work go.work.sum ./
COPY pkg/go.mod pkg/go.sum ./pkg/
COPY proto/go.mod proto/go.sum ./proto/

# Download shared deps
RUN cd pkg && go mod download
RUN cd proto && go mod download

# The service source code is mounted via volumes
CMD ["air", "-c", ".air.toml"]
