// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/media/v1/media.proto

package mediav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMediaMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaMetadataRequest) Reset() {
	*x = GetMediaMetadataRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaMetadataRequest) ProtoMessage() {}

func (x *GetMediaMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMediaMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *GetMediaMetadataRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type GetMediaMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	FileType      string                 `protobuf:"bytes,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Width         int32                  `protobuf:"varint,7,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`
	DurationMs    int64                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaMetadataResponse) Reset() {
	*x = GetMediaMetadataResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaMetadataResponse) ProtoMessage() {}

func (x *GetMediaMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMediaMetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *GetMediaMetadataResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *GetMediaMetadataResponse) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *GetMediaMetadataResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetMediaMetadataResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *GetMediaMetadataResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetMediaMetadataResponse) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *GetMediaMetadataResponse) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetMediaMetadataResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GetMediaMetadataResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_proto_media_v1_media_proto protoreflect.FileDescriptor

const file_proto_media_v1_media_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/media/v1/media.proto\x12\bmedia.v1\"4\n" +
	"\x17GetMediaMetadataRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"\x94\x02\n" +
	"\x18GetMediaMetadataResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1b\n" +
	"\tfile_type\x18\x02 \x01(\tR\bfileType\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12#\n" +
	"\rthumbnail_url\x18\x06 \x01(\tR\fthumbnailUrl\x12\x14\n" +
	"\x05width\x18\a \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\b \x01(\x05R\x06height\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs2i\n" +
	"\fMediaService\x12Y\n" +
	"\x10GetMediaMetadata\x12!.media.v1.GetMediaMetadataRequest\x1a\".media.v1.GetMediaMetadataResponseB:Z8github.com/whatsapp-clone/backend/proto/media/v1;mediav1b\x06proto3"

var (
	file_proto_media_v1_media_proto_rawDescOnce sync.Once
	file_proto_media_v1_media_proto_rawDescData []byte
)

func file_proto_media_v1_media_proto_rawDescGZIP() []byte {
	file_proto_media_v1_media_proto_rawDescOnce.Do(func() {
		file_proto_media_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_media_v1_media_proto_rawDesc), len(file_proto_media_v1_media_proto_rawDesc)))
	})
	return file_proto_media_v1_media_proto_rawDescData
}

var file_proto_media_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_media_v1_media_proto_goTypes = []any{
	(*GetMediaMetadataRequest)(nil),  // 0: media.v1.GetMediaMetadataRequest
	(*GetMediaMetadataResponse)(nil), // 1: media.v1.GetMediaMetadataResponse
}
var file_proto_media_v1_media_proto_depIdxs = []int32{
	0, // 0: media.v1.MediaService.GetMediaMetadata:input_type -> media.v1.GetMediaMetadataRequest
	1, // 1: media.v1.MediaService.GetMediaMetadata:output_type -> media.v1.GetMediaMetadataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_media_v1_media_proto_init() }
func file_proto_media_v1_media_proto_init() {
	if File_proto_media_v1_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_media_v1_media_proto_rawDesc), len(file_proto_media_v1_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_media_v1_media_proto_goTypes,
		DependencyIndexes: file_proto_media_v1_media_proto_depIdxs,
		MessageInfos:      file_proto_media_v1_media_proto_msgTypes,
	}.Build()
	File_proto_media_v1_media_proto = out.File
	file_proto_media_v1_media_proto_goTypes = nil
	file_proto_media_v1_media_proto_depIdxs = nil
}
