// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/chat/v1/chat.proto

package chatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChatParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatParticipantsRequest) Reset() {
	*x = GetChatParticipantsRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatParticipantsRequest) ProtoMessage() {}

func (x *GetChatParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatParticipantsRequest.ProtoReflect.Descriptor instead.
func (*GetChatParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *GetChatParticipantsRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type GetChatParticipantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatParticipantsResponse) Reset() {
	*x = GetChatParticipantsResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatParticipantsResponse) ProtoMessage() {}

func (x *GetChatParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatParticipantsResponse.ProtoReflect.Descriptor instead.
func (*GetChatParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *GetChatParticipantsResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type IsMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberRequest) Reset() {
	*x = IsMemberRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberRequest) ProtoMessage() {}

func (x *IsMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberRequest.ProtoReflect.Descriptor instead.
func (*IsMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *IsMemberRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *IsMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberResponse) Reset() {
	*x = IsMemberResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberResponse) ProtoMessage() {}

func (x *IsMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberResponse.ProtoReflect.Descriptor instead.
func (*IsMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *IsMemberResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

type CheckChatPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckChatPermissionRequest) Reset() {
	*x = CheckChatPermissionRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckChatPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckChatPermissionRequest) ProtoMessage() {}

func (x *CheckChatPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckChatPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckChatPermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *CheckChatPermissionRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *CheckChatPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckChatPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,2,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	IsAdminOnly   bool                   `protobuf:"varint,3,opt,name=is_admin_only,json=isAdminOnly,proto3" json:"is_admin_only,omitempty"` // true if only admins can send messages
	ChatType      string                 `protobuf:"bytes,4,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"`             // "direct" or "group"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckChatPermissionResponse) Reset() {
	*x = CheckChatPermissionResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckChatPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckChatPermissionResponse) ProtoMessage() {}

func (x *CheckChatPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckChatPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckChatPermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *CheckChatPermissionResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *CheckChatPermissionResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *CheckChatPermissionResponse) GetIsAdminOnly() bool {
	if x != nil {
		return x.IsAdminOnly
	}
	return false
}

func (x *CheckChatPermissionResponse) GetChatType() string {
	if x != nil {
		return x.ChatType
	}
	return ""
}

var File_proto_chat_v1_chat_proto protoreflect.FileDescriptor

const file_proto_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x18proto/chat/v1/chat.proto\x12\achat.v1\"5\n" +
	"\x1aGetChatParticipantsRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"8\n" +
	"\x1bGetChatParticipantsResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"C\n" +
	"\x0fIsMemberRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x10IsMemberResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\"N\n" +
	"\x1aCheckChatPermissionRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x96\x01\n" +
	"\x1bCheckChatPermissionResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\x12\x19\n" +
	"\bis_admin\x18\x02 \x01(\bR\aisAdmin\x12\"\n" +
	"\ris_admin_only\x18\x03 \x01(\bR\visAdminOnly\x12\x1b\n" +
	"\tchat_type\x18\x04 \x01(\tR\bchatType2\x92\x02\n" +
	"\vChatService\x12`\n" +
	"\x13GetChatParticipants\x12#.chat.v1.GetChatParticipantsRequest\x1a$.chat.v1.GetChatParticipantsResponse\x12?\n" +
	"\bIsMember\x12\x18.chat.v1.IsMemberRequest\x1a\x19.chat.v1.IsMemberResponse\x12`\n" +
	"\x13CheckChatPermission\x12#.chat.v1.CheckChatPermissionRequest\x1a$.chat.v1.CheckChatPermissionResponseB8Z6github.com/whatsapp-clone/backend/proto/chat/v1;chatv1b\x06proto3"

var (
	file_proto_chat_v1_chat_proto_rawDescOnce sync.Once
	file_proto_chat_v1_chat_proto_rawDescData []byte
)

func file_proto_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_v1_chat_proto_rawDesc), len(file_proto_chat_v1_chat_proto_rawDesc)))
	})
	return file_proto_chat_v1_chat_proto_rawDescData
}

var file_proto_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_chat_v1_chat_proto_goTypes = []any{
	(*GetChatParticipantsRequest)(nil),  // 0: chat.v1.GetChatParticipantsRequest
	(*GetChatParticipantsResponse)(nil), // 1: chat.v1.GetChatParticipantsResponse
	(*IsMemberRequest)(nil),             // 2: chat.v1.IsMemberRequest
	(*IsMemberResponse)(nil),            // 3: chat.v1.IsMemberResponse
	(*CheckChatPermissionRequest)(nil),  // 4: chat.v1.CheckChatPermissionRequest
	(*CheckChatPermissionResponse)(nil), // 5: chat.v1.CheckChatPermissionResponse
}
var file_proto_chat_v1_chat_proto_depIdxs = []int32{
	0, // 0: chat.v1.ChatService.GetChatParticipants:input_type -> chat.v1.GetChatParticipantsRequest
	2, // 1: chat.v1.ChatService.IsMember:input_type -> chat.v1.IsMemberRequest
	4, // 2: chat.v1.ChatService.CheckChatPermission:input_type -> chat.v1.CheckChatPermissionRequest
	1, // 3: chat.v1.ChatService.GetChatParticipants:output_type -> chat.v1.GetChatParticipantsResponse
	3, // 4: chat.v1.ChatService.IsMember:output_type -> chat.v1.IsMemberResponse
	5, // 5: chat.v1.ChatService.CheckChatPermission:output_type -> chat.v1.CheckChatPermissionResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_chat_v1_chat_proto_init() }
func file_proto_chat_v1_chat_proto_init() {
	if File_proto_chat_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_v1_chat_proto_rawDesc), len(file_proto_chat_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_v1_chat_proto_depIdxs,
		MessageInfos:      file_proto_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_v1_chat_proto = out.File
	file_proto_chat_v1_chat_proto_goTypes = nil
	file_proto_chat_v1_chat_proto_depIdxs = nil
}
